stages:
  - setup
  - test

setup_z3:
  stage: setup
  image: python:3.11
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - echo "Setup completed."

test_z3:
  stage: test
  image: python:3.11
  before_script:
    - source venv/bin/activate
  script:
    - python z3/main.py
