name: Test z3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  z3_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ghc cabal-install

      - name: Install Haskell dependencies
        run: |
          cabal update
          cabal install --lib testing-feat
          cabal install --lib size-based

      - name: Clone ET_private
        run: |
          git clone --branch smt-solver-evolution https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/wintered/ET_private.git
          echo "Listing contents after cloning:"
          ls -la ET_private
        env:
          GIT_USER: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python environment
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install poetry

      - name: Install dependencies using Poetry inside ET_private
        run: |
          cd ET_private
          source ../venv/bin/activate
          poetry install

      - name: Install dependencies and run tests
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          python -m z3.main
