name: Test z3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  z3_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y ghc cabal-install sqlite3

      - name: Install Haskell dependencies
        run: |
          cabal update
          cabal install --lib testing-feat
          cabal install --lib size-based

      - name: Clone ET_private
        run: |
          git clone --branch smt-solver-evolution https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/wintered/ET_private.git
        env:
          GIT_USER: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python environment
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install poetry

      - name: Install dependencies using Poetry inside ET_private
        run: |
          cd ET_private
          source ../venv/bin/activate
          poetry install
          cd ..

      - name: Copy necessary files
        run: |
          mkdir -p et_config
          cp ET_private/z_old/et/data/*.{cfg,g4} et_config/

      - name: Install dependencies and run tests
        env:
          NUM_TESTS: ${{ vars.NUM_TESTS }}
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          python -m z3.main

      - name: Run experiment for each theory
        env:
          NUM_TESTS: ${{ vars.NUM_TESTS }}
        run: |
          chmod +x ./scripts/run_exp.sh
          chmod +x ./binaries/cvc5-1.2.0
          chmod +x ./binaries/z3-4.8.11
          chmod +x ./binaries/z3-4.13.3
          for theory in $(cat ./supported_theories/z3); do
            ./scripts/run_exp.sh "$theory" "$NUM_TESTS" "./solvers.cfg"
          done

      - name: Store experiment results
        run: |
          chmod +x ./scripts/create_db.sh
          for theory in $(cat ./supported_theories/z3); do
            ./scripts/create_db.sh "$theory"
          done

      - name: Gather statistics
        env:
          NUM_TESTS: ${{ vars.NUM_TESTS }}
        run: |
          chmod +x ./scripts/gather_statistics.sh
          ./scripts/gather_statistics.sh ./results